# Generated by Django 4.2.7 on 2023-11-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_car_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extras',
            name='price',
        ),
    ]
