# Generated by Django 4.2.7 on 2023-12-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_extras_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='car_images'),
        ),
    ]
