# Generated by Django 4.2.7 on 2024-01-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_currencyprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyprice',
            name='symbol',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
