# Generated by Django 4.2.7 on 2023-12-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_api', '0002_remove_car_year_car_price_alter_car_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
