# Generated by Django 4.2.7 on 2023-12-10 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_api', '0003_alter_car_make_alter_car_model_alter_car_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
