# Generated by Django 4.2.7 on 2023-12-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_api', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarAPI',
        ),
    ]
